name: CI

on:
    pull_request:
    push:
        branches: [main]
    workflow_call:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Install libdbus-1-dev
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends \
                      libdbus-1-dev=1.14.10-4ubuntu4.1

            - name: Install Rust toolchain
              run: rustup show

            - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

            - name: cargo fmt --check
              run: cargo fmt --all -- --check

            - name: cargo clippy
              run: cargo clippy --workspace --tests -- -D warnings

            - name: cargo test
              run: cargo test --workspace
